In [2]:
import pandas as pd
import numpy as np

In [3]:
housing_data = pd.read_csv('housing.csv')

In [4]:
housing_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-117.61,34.13,21.0,8416.0,1386.0,4308.0,1341.0,4.4611,INLAND,164600.0
1,-117.37,33.98,52.0,201.0,44.0,130.0,24.0,2.0250,INLAND,125000.0
2,-118.34,33.89,36.0,2274.0,411.0,1232.0,423.0,5.3730,<1H OCEAN,244500.0
3,-118.92,35.13,29.0,1297.0,262.0,909.0,253.0,1.9236,INLAND,106300.0
4,-121.80,37.23,18.0,3179.0,526.0,1663.0,507.0,5.9225,<1H OCEAN,265800.0
...,...,...,...,...,...,...,...,...,...,...
16507,-119.53,36.55,34.0,2065.0,343.0,1041.0,313.0,3.2917,INLAND,111500.0
16508,-122.40,37.73,50.0,1947.0,411.0,1170.0,384.0,3.4769,NEAR BAY,238700.0
16509,-118.41,33.92,29.0,1436.0,401.0,674.0,343.0,3.6389,<1H OCEAN,275000.0
16510,-117.08,32.62,36.0,1674.0,309.0,818.0,307.0,3.4773,NEAR OCEAN,150400.0
16511,-117.05,32.72,35.0,3669.0,617.0,1694.0,585.0,3.9485,NEAR OCEAN,133900.0

In [6]:
def one_hot(features:list, data:pd.DataFrame):
    
    """generic one hot encoding function for a list of features"""
    
    #copy to avoid overwriting original data
    returnArray = data
    for ftr in features:
        uniqueList = np.unique(data[ftr])
        for val in uniqueList:
            colName = ftr + str(val)
            def row_lambda(row):
                if row[ftr] == val:
                    return 1
                else:  
                    return 0
            returnArray[colName] = returnArray.apply(row_lambda, axis=1)
    
    return returnArray

In [7]:
array = one_hot(['ocean_proximity'], housing_data)

In [8]:
array

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value,ocean_proximity<1H OCEAN,ocean_proximityINLAND,ocean_proximityISLAND,ocean_proximityNEAR BAY,ocean_proximityNEAR OCEAN
0,-117.61,34.13,21.0,8416.0,1386.0,4308.0,1341.0,4.4611,INLAND,164600.0,0,1,0,0,0
1,-117.37,33.98,52.0,201.0,44.0,130.0,24.0,2.0250,INLAND,125000.0,0,1,0,0,0
2,-118.34,33.89,36.0,2274.0,411.0,1232.0,423.0,5.3730,<1H OCEAN,244500.0,1,0,0,0,0
3,-118.92,35.13,29.0,1297.0,262.0,909.0,253.0,1.9236,INLAND,106300.0,0,1,0,0,0
4,-121.80,37.23,18.0,3179.0,526.0,1663.0,507.0,5.9225,<1H OCEAN,265800.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,-119.53,36.55,34.0,2065.0,343.0,1041.0,313.0,3.2917,INLAND,111500.0,0,1,0,0,0
16508,-122.40,37.73,50.0,1947.0,411.0,1170.0,384.0,3.4769,NEAR BAY,238700.0,0,0,0,1,0
16509,-118.41,33.92,29.0,1436.0,401.0,674.0,343.0,3.6389,<1H OCEAN,275000.0,1,0,0,0,0
16510,-117.08,32.62,36.0,1674.0,309.0,818.0,307.0,3.4773,NEAR OCEAN,150400.0,0,0,0,0,1
16511,-117.05,32.72,35.0,3669.0,617.0,1694.0,585.0,3.9485,NEAR OCEAN,133900.0,0,0,0,0,1

In [9]:
array.isna().sum().to_frame(name='NaN Count')

                           NaN Count
longitude                          0
latitude                           0
housing_median_age                 0
total_rooms                        0
total_bedrooms                   168
population                         0
households                         0
median_income                      0
ocean_proximity                    0
median_house_value                 0
ocean_proximity<1H OCEAN           0
ocean_proximityINLAND              0
ocean_proximityISLAND              0
ocean_proximityNEAR BAY            0
ocean_proximityNEAR OCEAN          0

In [11]:
housing_data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity<1H OCEAN,ocean_proximityINLAND,ocean_proximityISLAND,ocean_proximityNEAR BAY,ocean_proximityNEAR OCEAN
count,16512.00000,16512.000000,16512.000000,16512.000000,16344.000000,16512.000000,16512.000000,16512.00000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000,16512.000000
mean,-119.55943,35.617896,28.669331,2639.225654,538.522026,1425.169513,499.902616,3.87329,207251.882994,0.442163,0.315104,0.000242,0.111737,0.130753
std,2.00348,2.134056,12.615046,2198.453859,425.256071,1147.038029,385.367776,1.91235,115687.033147,0.496659,0.464571,0.015563,0.315052,0.337141
min,-124.35000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.49990,14999.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-121.78250,33.930000,18.000000,1446.000000,295.000000,788.000000,279.000000,2.56250,120000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-118.49000,34.250000,29.000000,2122.000000,435.000000,1165.000000,410.000000,3.53410,179800.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,-118.00000,37.710000,37.000000,3143.000000,647.000000,1718.000000,604.000000,4.73975,264525.000000,1.000000,1.000000,0.000000,0.000000,0.000000
max,-114.31000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.00010,500001.000000,1.000000,1.000000,1.000000,1.000000,1.000000